# Generated by Django 5.0.6 on 2024-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1024)),
                ('text', models.CharField(default='', max_length=1024)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1024)),
                ('text', models.CharField(max_length=1024)),
                ('number', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
